[2024-06-14T09:21:54.237+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Spark_dag.spark_query_csv manual__2024-06-14T09:20:46.110814+00:00 [queued]>
[2024-06-14T09:21:54.242+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Spark_dag.spark_query_csv manual__2024-06-14T09:20:46.110814+00:00 [queued]>
[2024-06-14T09:21:54.244+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2024-06-14T09:21:54.260+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): spark_query_csv> on 2024-06-14 09:20:46.110814+00:00
[2024-06-14T09:21:54.277+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Spark_dag', 'spark_query_csv', 'manual__2024-06-14T09:20:46.110814+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/Spark_dag.py', '--cfg-path', '/tmp/tmp9dpm7tnn']
[2024-06-14T09:21:54.281+0000] {standard_task_runner.py:85} INFO - Job 49: Subtask spark_query_csv
[2024-06-14T09:21:54.270+0000] {standard_task_runner.py:57} INFO - Started process 4040 to run task
[2024-06-14T09:21:54.356+0000] {task_command.py:415} INFO - Running <TaskInstance: Spark_dag.spark_query_csv manual__2024-06-14T09:20:46.110814+00:00 [running]> on host 963b3fbfa4c9
[2024-06-14T09:21:54.456+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Spark_dag' AIRFLOW_CTX_TASK_ID='spark_query_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-06-14T09:20:46.110814+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-14T09:20:46.110814+00:00'
[2024-06-14T09:21:54.468+0000] {base.py:73} INFO - Using connection ID 'Spark_connection' for task execution.
[2024-06-14T09:21:54.471+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --conf spark.master=spark://spark-master:7077 --conf spark.hadoop.fs.s3a.endpoint=http://host.docker.internal:9000 --conf spark.hadoop.fs.s3a.access.key=fPMHZA3ZV0g2so9iydgd --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.path.style.access=true --conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem --name arrow-spark --deploy-mode client /opt/bitnami/spark/jobs/pyspark_test.py s3a://data-lake/allstockprice.csv fPMHZA3ZV0g2so9iydgd 2wY04v8tSwkpVb054WFro0AP6SJ4mjvHbVHurSUp
[2024-06-14T09:21:54.697+0000] {spark_submit.py:571} INFO - /home/***/.local/lib/python3.9/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-06-14T09:21:56.378+0000] {spark_submit.py:571} INFO - python3: can't open file '/opt/bitnami/spark/jobs/pyspark_test.py': [Errno 2] No such file or directory
[2024-06-14T09:21:56.412+0000] {spark_submit.py:571} INFO - 24/06/14 09:21:56 INFO ShutdownHookManager: Shutdown hook called
[2024-06-14T09:21:56.441+0000] {spark_submit.py:571} INFO - 24/06/14 09:21:56 INFO ShutdownHookManager: Deleting directory /tmp/spark-f24f4ab2-4029-44e8-8959-54b4d41f9898
[2024-06-14T09:21:56.506+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.master=spark://spark-master:7077 --conf spark.hadoop.fs.s3a.endpoint=http://host.docker.internal:9000 --conf spark.hadoop.fs.s3a.access.key=fPMHZA3ZV0g2so9iydgd --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.path.style.access=true --conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem --name arrow-spark --deploy-mode client /opt/bitnami/spark/jobs/pyspark_test.py s3a://data-lake/allstockprice.csv fPMHZA3ZV0g2so9iydgd 2wY04v8tSwkpVb054WFro0AP6SJ4mjvHbVHurSUp. Error code is: 2.
[2024-06-14T09:21:56.518+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=Spark_dag, task_id=spark_query_csv, execution_date=20240614T092046, start_date=20240614T092154, end_date=20240614T092156
[2024-06-14T09:21:56.534+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 49 for task spark_query_csv (Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.master=spark://spark-master:7077 --conf spark.hadoop.fs.s3a.endpoint=http://host.docker.internal:9000 --conf spark.hadoop.fs.s3a.access.key=fPMHZA3ZV0g2so9iydgd --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.path.style.access=true --conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem --name arrow-spark --deploy-mode client /opt/bitnami/spark/jobs/pyspark_test.py s3a://data-lake/allstockprice.csv fPMHZA3ZV0g2so9iydgd 2wY04v8tSwkpVb054WFro0AP6SJ4mjvHbVHurSUp. Error code is: 2.; 4040)
[2024-06-14T09:21:56.549+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-06-14T09:21:56.583+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
